"""Drone control service — sweep scan and movement primitives."""

from __future__ import annotations

import math
from typing import Any, Callable, Coroutine


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

# A coroutine factory that, given a drone ID and a waypoint dict, returns the
# sensor "view" for that position.  In production this calls the gRPC client;
# in tests it is replaced by a simple async stub.
ViewFetcher = Callable[
    [str, dict[str, Any]], Coroutine[Any, Any, dict[str, Any]]
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_sweep_waypoints(
    center_x: float,
    center_y: float,
    center_z: float,
    radius: float,
    levels: list[float],
    points_per_level: int = 8,
) -> list[dict[str, Any]]:
    """Generate a circular sweep pattern around a building centre.

    Each waypoint sits on the perimeter of a circle of *radius* around the
    centre column, at every height in *levels*.

    Args:
        center_x: World X coordinate of the building centre.
        center_y: Ground Y of the building (used as reference).
        center_z: World Z coordinate of the building centre.
        radius: Distance from centre for the sweep orbit.
        levels: List of Y (height) values to scan at.
        points_per_level: Number of evenly‑spaced points on each orbit ring.

    Returns:
        Ordered list of waypoint dicts, each with keys
        ``x``, ``y``, ``z``, ``level_y``.
    """
    waypoints: list[dict[str, Any]] = []
    for level_y in levels:
        for i in range(points_per_level):
            angle = 2 * math.pi * i / points_per_level
            waypoints.append(
                {
                    "x": center_x + radius * math.cos(angle),
                    "y": level_y,
                    "z": center_z + radius * math.sin(angle),
                    "level_y": level_y,
                }
            )
    return waypoints


def _compile_sweep_summary(waypoint_reports: list[dict[str, Any]]) -> str:
    """Produce a human‑readable summary from aggregated waypoint reports.

    The summary reflects the *visible* survivor count stored under the
    ``survivors_in_range`` key of each report.  A report entry carries the
    *maximum* of:

    * the number of survivors the drone sensor directly detected (i.e. those
      that triggered a visual ray in the 3‑D twin), and
    * the ``survivors_in_range`` count returned by the sensor view payload.

    This means the text correctly says "X survivor(s) detected" whenever any
    red ray is rendered on‑screen, rather than always falling back to the
    geometric‑radius‑only count which can be zero even while survivors are
    visible.

    Args:
        waypoint_reports: List of per‑waypoint result dicts produced inside
            :func:`sweep_scan_building`.

    Returns:
        A plain‑text summary string suitable for display in the tactical
        dashboard.
    """
    total_survivors = sum(r["survivors_in_range"] for r in waypoint_reports)

    if total_survivors == 0:
        return "No heat signature detected during sweep scan."

    # Collect unique survivor IDs to avoid double‑counting across waypoints.
    seen_ids: set[str] = set()
    for report in waypoint_reports:
        for survivor in report.get("detected_survivors", []):
            sid = survivor.get("id")
            if sid:
                seen_ids.add(str(sid))

    unique_count = len(seen_ids) if seen_ids else total_survivors
    noun = "survivor" if unique_count == 1 else "survivors"
    return (
        f"Sweep complete — {unique_count} {noun} detected. "
        "Coordinates logged. Recommend immediate extraction."
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def sweep_scan_building(
    drone_id: str,
    center_x: float,
    center_y: float,
    center_z: float,
    scan_radius: float,
    levels: list[float],
    get_view: ViewFetcher,
    points_per_level: int = 8,
) -> dict[str, Any]:
    """Execute a full orbital sweep scan around a building and return results.

    The drone visits every waypoint generated by :func:`_build_sweep_waypoints`
    and, at each stop, queries the sensor view via *get_view*.  The resulting
    reports aggregate both the geometrically‑filtered survivors
    (``detected_survivors_within_scan_radius``) **and** the full set of
    sensor‑visible survivors (``detected_survivors``).

    The ``survivors_in_range`` field in each report is set to the *maximum* of:

    1. ``len(detected_survivors)`` — survivors the drone sensor can see from
       this waypoint (these are the ones that produce a rendered ray in the
       3‑D digital twin).
    2. ``view["survivors_in_range"]`` — the integer count returned directly by
       the sensor model, which may include survivors whose distance record is
       absent or imprecise.

    This ensures the final summary text always reflects whether a survivor
    was visually detected, fixing the bug where the summary reported
    "no heat signature detected" even while red rays were rendered on‑screen.

    Args:
        drone_id: Asset identifier of the scanning drone.
        center_x: World X coordinate of the building centre.
        center_y: Ground Y of the building.
        center_z: World Z coordinate of the building centre.
        scan_radius: Maximum distance (world units) from the drone at which
            a survivor counts as *within scan radius* for the geometric filter.
        levels: List of Y (height) values at which to orbit the building.
        get_view: Async callable ``(drone_id, waypoint) → view_dict``.
            In production this calls the gRPC sensor endpoint; in tests it is
            replaced by a stub.
        points_per_level: Number of evenly‑spaced orbit points per level.

    Returns:
        A dict with keys:

        * ``waypoint_reports`` — list of per‑waypoint result dicts.
        * ``summary`` — human‑readable result string.
        * ``total_survivors_visible`` — sum of ``survivors_in_range`` across
          all waypoints (may double‑count survivors seen from multiple stops).
    """
    waypoints = _build_sweep_waypoints(
        center_x, center_y, center_z, scan_radius, levels, points_per_level
    )

    waypoint_reports: list[dict[str, Any]] = []

    for index, wp in enumerate(waypoints):
        view: dict[str, Any] = await get_view(drone_id, wp)

        # Survivors reported as individually visible by the sensor model.
        detected_survivors: list[dict[str, Any]] = view.get(
            "detected_survivors", []
        )

        # Geometric sub‑filter: survivors whose recorded distance is within
        # scan_radius.  Used for the tighter "within radius" count.
        survivors_in_scan_radius = [
            det
            for det in detected_survivors
            if isinstance(det.get("distance"), (int, float))
            and math.isfinite(float(det["distance"]))
            and float(det["distance"]) <= scan_radius
        ]

        # ------------------------------------------------------------------ #
        # FIX: Align sweep summary with rendered scan rays / sensor visibility.
        #
        # Previously survivors_in_range was set to len(survivors_in_scan_radius)
        # (purely geometric).  This caused the summary to always say
        # "no heat signature detected" whenever all survivors happened to be
        # outside the geometric radius—even when the drone could visually see
        # them (red ray rendered in the 3‑D twin).
        #
        # We now take the maximum of:
        #   • len(detected_survivors)       — sensor‑visible count
        #   • view["survivors_in_range"]    — integer from the view payload
        # so the count (and hence the summary text) matches what is actually
        # rendered on‑screen.
        # ------------------------------------------------------------------ #
        view_survivor_count = view.get("survivors_in_range")
        survivors_visible_count = len(detected_survivors)
        if isinstance(view_survivor_count, int):
            survivors_visible_count = max(
                survivors_visible_count, view_survivor_count
            )
        survivors_within_radius_count = len(survivors_in_scan_radius)

        waypoint_reports.append(
            {
                "index": index,
                "x": wp["x"],
                "y": wp["y"],
                "z": wp["z"],
                "level_y": wp["level_y"],
                # Keep sweep summary aligned with rendered scan rays / sensor
                # visibility.
                "survivors_in_range": survivors_visible_count,
                "survivors_within_scan_radius": survivors_within_radius_count,
                "detected_survivors": detected_survivors,
                "detected_survivors_within_scan_radius": survivors_in_scan_radius,
                "sensor_summary": view.get("summary", ""),
            }
        )

    summary = _compile_sweep_summary(waypoint_reports)
    total_survivors_visible = sum(
        r["survivors_in_range"] for r in waypoint_reports
    )

    return {
        "waypoint_reports": waypoint_reports,
        "summary": summary,
        "total_survivors_visible": total_survivors_visible,
    }
