from __future__ import annotations

import asyncio
import os
import sys
from dataclasses import dataclass
from functools import partial

import grpc

# Stubs generated by scripts/gen_proto.sh
_stub_dir = os.path.dirname(__file__)
sys.path.insert(0, _stub_dir)

try:
    import beacon_pb2
    import beacon_pb2_grpc
except ImportError as exc:
    raise ImportError(
        "gRPC stubs not found in backend/grpc/. Run: bash scripts/gen_proto.sh"
    ) from exc

# Per-call gRPC deadline.  Keeps individual RPC calls from blocking the event
# loop indefinitely if the drone container is slow or the thread pool is full.
_GRPC_TIMEOUT_S = 15.0


@dataclass
class _DroneConnection:
    host: str
    port: int
    channel: grpc.Channel
    stub: beacon_pb2_grpc.DroneControlStub


class DroneGrpcClient:
    """Manages gRPC connections to multiple drone nodes."""

    def __init__(self) -> None:
        self._connections: dict[str, _DroneConnection] = {}

    def register(self, asset_id: str, host: str, port: int) -> None:
        asset_id = asset_id.upper()
        if asset_id in self._connections:
            self._connections[asset_id].channel.close()
        channel = grpc.insecure_channel(f"{host}:{port}")
        stub = beacon_pb2_grpc.DroneControlStub(channel)
        self._connections[asset_id] = _DroneConnection(host, port, channel, stub)

    def _stub(self, asset_id: str) -> beacon_pb2_grpc.DroneControlStub:
        conn = self._connections.get(asset_id.upper())
        if not conn:
            raise KeyError(f"No gRPC connection for {asset_id}. Call /uplink first.")
        return conn.stub

    async def _call(self, fn, *args, **kwargs):
        """Run a blocking synchronous gRPC call in the default thread executor."""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, partial(fn, *args, **kwargs))

    async def move_to(
        self, asset_id: str, x: float, y: float, z: float, speed: float = 5.0
    ) -> dict:
        stub = self._stub(asset_id)
        resp = await self._call(
            stub.MoveTo,
            beacon_pb2.MoveToRequest(asset_id=asset_id, x=x, y=y, z=z, speed=speed),
            timeout=_GRPC_TIMEOUT_S,
        )
        return {"success": resp.success, "message": resp.message}

    async def get_status(self, asset_id: str) -> dict:
        stub = self._stub(asset_id)
        resp = await self._call(
            stub.GetStatus,
            beacon_pb2.StatusRequest(asset_id=asset_id),
            timeout=_GRPC_TIMEOUT_S,
        )
        return {
            "asset_id": resp.asset_id,
            "x": resp.x, "y": resp.y, "z": resp.z,
            "battery": resp.battery,
            "status": resp.status,
            "timestamp_ms": resp.timestamp_ms,
        }

    async def return_to_base(self, asset_id: str) -> dict:
        stub = self._stub(asset_id)
        resp = await self._call(
            stub.ReturnToBase,
            beacon_pb2.ReturnRequest(asset_id=asset_id),
            timeout=_GRPC_TIMEOUT_S,
        )
        return {"success": resp.success, "message": resp.message}

    async def scan_area(
        self, asset_id: str, cx: float, cy: float, cz: float, radius: float = 5.0
    ) -> dict:
        stub = self._stub(asset_id)
        resp = await self._call(
            stub.ScanArea,
            beacon_pb2.ScanAreaRequest(
                asset_id=asset_id, cx=cx, cy=cy, cz=cz, radius=radius
            ),
            timeout=_GRPC_TIMEOUT_S,
        )
        return {"success": resp.success, "message": resp.message}

    async def end_scan(self, asset_id: str) -> dict:
        """End the scan session and return the drone to IDLE."""
        return await self.scan_area(asset_id, cx=0, cy=0, cz=0, radius=-1)

    async def get_view(
        self,
        asset_id: str,
        heading_deg: float = 0.0,
        detection_range: float = 0.0,
    ) -> dict:
        stub = self._stub(asset_id)
        resp = await self._call(
            stub.GetView,
            beacon_pb2.ViewRequest(
                asset_id=asset_id,
                heading_deg=heading_deg,
                range=detection_range,
            ),
            timeout=_GRPC_TIMEOUT_S,
        )
        objects = [
            {
                "object_type": o.object_type,
                "object_id": o.object_id,
                "x": o.x, "y": o.y, "z": o.z,
                "distance": o.distance,
                "direction": o.direction,
                "detail": o.detail,
            }
            for o in resp.objects
        ]
        return {
            "asset_id": resp.asset_id,
            "objects": objects,
            "terrain": resp.terrain,
            "altitude_agl": resp.altitude_agl,
            "obstacle_ahead": resp.obstacle_ahead,
            "nearest_obstacle_dist": resp.nearest_obstacle_dist,
            "nearby_obstacles": resp.nearby_obstacles,
            "survivors_in_range": resp.survivors_in_range,
            "over_flood": resp.over_flood,
            "summary": resp.summary,
        }

    def registered_asset_ids(self) -> list[str]:
        """Return all asset IDs that have an active gRPC connection."""
        return list(self._connections.keys())

    def close_all(self) -> None:
        for conn in self._connections.values():
            conn.channel.close()
        self._connections.clear()
