from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from typing import Any

import grpc

# Stubs generated by scripts/gen_proto.sh
_stub_dir = os.path.dirname(__file__)
sys.path.insert(0, _stub_dir)

try:
    import beacon_pb2
    import beacon_pb2_grpc
except ImportError as exc:
    raise ImportError(
        "gRPC stubs not found in backend/grpc/. Run: bash scripts/gen_proto.sh"
    ) from exc


@dataclass
class _DroneConnection:
    host: str
    port: int
    channel: grpc.Channel
    stub: beacon_pb2_grpc.DroneControlStub


class DroneGrpcClient:
    """Manages gRPC connections to multiple drone nodes."""

    def __init__(self) -> None:
        self._connections: dict[str, _DroneConnection] = {}

    def register(self, asset_id: str, host: str, port: int) -> None:
        if asset_id in self._connections:
            self._connections[asset_id].channel.close()
        channel = grpc.insecure_channel(f"{host}:{port}")
        stub = beacon_pb2_grpc.DroneControlStub(channel)
        self._connections[asset_id] = _DroneConnection(host, port, channel, stub)

    def _stub(self, asset_id: str) -> beacon_pb2_grpc.DroneControlStub:
        conn = self._connections.get(asset_id)
        if not conn:
            raise KeyError(f"No gRPC connection for {asset_id}. Call /uplink first.")
        return conn.stub

    async def move_to(
        self, asset_id: str, x: float, y: float, z: float, speed: float = 5.0
    ) -> dict:
        stub = self._stub(asset_id)
        resp = stub.MoveTo(
            beacon_pb2.MoveToRequest(asset_id=asset_id, x=x, y=y, z=z, speed=speed)
        )
        return {"success": resp.success, "message": resp.message}

    async def get_status(self, asset_id: str) -> dict:
        stub = self._stub(asset_id)
        resp = stub.GetStatus(beacon_pb2.StatusRequest(asset_id=asset_id))
        return {
            "asset_id": resp.asset_id,
            "x": resp.x, "y": resp.y, "z": resp.z,
            "battery": resp.battery,
            "status": resp.status,
            "timestamp_ms": resp.timestamp_ms,
        }

    async def return_to_base(self, asset_id: str) -> dict:
        stub = self._stub(asset_id)
        resp = stub.ReturnToBase(beacon_pb2.ReturnRequest(asset_id=asset_id))
        return {"success": resp.success, "message": resp.message}

    async def scan_area(
        self, asset_id: str, cx: float, cy: float, cz: float, radius: float = 5.0
    ) -> dict:
        stub = self._stub(asset_id)
        resp = stub.ScanArea(
            beacon_pb2.ScanAreaRequest(
                asset_id=asset_id, cx=cx, cy=cy, cz=cz, radius=radius
            )
        )
        return {"success": resp.success, "message": resp.message}

    def close_all(self) -> None:
        for conn in self._connections.values():
            conn.channel.close()
        self._connections.clear()
