"""Stable API facades consumed by app routes and MCP tools."""

from backend.services.api.control import (
    add_supply_station,
    assign_fleet_to_buildings,
    deploy_swarm,
    dispatch_supply_to_building,
    find_buildings_in_area,
    find_survivors_in_area,
    get_drone_status,
    get_drone_view,
    list_all_drones,
    list_supply_stations,
    move_drone_to,
    parallel_fleet_scan,
    parallel_fleet_supply,
    plan_route,
    plan_sweep_pattern,
    recall_swarm,
    remove_supply_station,
    resolve_scan_target,
    return_to_base,
    scan_area,
    set_drone_speed,
    sweep_scan_building,
)
from backend.services.fleet import (
    discover_fleet,
    ensure_uplink,
    restore_registered_connections,
    scan_frequencies,
)

__all__ = [
    "add_supply_station",
    "assign_fleet_to_buildings",
    "deploy_swarm",
    "discover_fleet",
    "dispatch_supply_to_building",
    "ensure_uplink",
    "find_buildings_in_area",
    "find_survivors_in_area",
    "get_drone_status",
    "get_drone_view",
    "list_all_drones",
    "list_supply_stations",
    "move_drone_to",
    "parallel_fleet_scan",
    "parallel_fleet_supply",
    "plan_route",
    "plan_sweep_pattern",
    "recall_swarm",
    "remove_supply_station",
    "resolve_scan_target",
    "restore_registered_connections",
    "return_to_base",
    "scan_area",
    "scan_frequencies",
    "set_drone_speed",
    "sweep_scan_building",
]
