CREATE TABLE IF NOT EXISTS mission_runs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_id        TEXT,
    asset_id             TEXT NOT NULL,
    prompt               TEXT NOT NULL,
    status               TEXT NOT NULL,
    started_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at             TIMESTAMPTZ,
    duration_ms          INTEGER,
    ttft_ms              INTEGER,
    tool_call_count      INTEGER NOT NULL DEFAULT 0,
    survivors_detected   INTEGER NOT NULL DEFAULT 0,
    survivors_rescued    INTEGER NOT NULL DEFAULT 0,
    result_summary       TEXT,
    error_message        TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mission_runs_created_at ON mission_runs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mission_runs_simulation ON mission_runs (simulation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mission_runs_status     ON mission_runs (status);
