CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id TEXT NOT NULL UNIQUE,
    asset_class TEXT NOT NULL DEFAULT 'scout_quadcopter',
    grpc_host TEXT NOT NULL,
    grpc_port INTEGER NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assets_registered_at ON assets (registered_at DESC);

CREATE TABLE IF NOT EXISTS mission_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id TEXT NOT NULL,
    command TEXT NOT NULL,
    params TEXT,
    result TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mission_logs_asset_id_created_at
    ON mission_logs (asset_id, created_at DESC);

CREATE TABLE IF NOT EXISTS licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key TEXT NOT NULL UNIQUE,
    org_name TEXT NOT NULL,
    expiry_date DATE NOT NULL,
    seat_count INTEGER NOT NULL DEFAULT 1,
    activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_licenses_is_active_id
    ON licenses (is_active, id DESC);
